%% FMR1_CIRCTRACK_SUMMARY

%% Read in data and create struct

group = fmr1CircTrack_1_buildDataStruct; %inialize struct
group = fmr1CircTrack_2_attachPfs(group);
group = fmr1CircTrack_3_tagLaps(group);
group = fmr1CircTrack_4_addSleepInfoToStruct(group);
group = fmr1CircTrack_5_getDecodingError(group); %also creates Figure 4
group = fmr1CircTrack_6_addReplayEventsToStruct(group);
fmr1CircTrack_7_detectSequences(group); %NOTE: This code detects sequence events using the methods 
% from Zheng et al. 2021. This method finds sequence events from the decoded probability
% distribution across the entire run session. While the figure in the paper ultimately using the
% method from Zhenget al. 2016, which uses the cut theta cycles (see Figure 5 below), the spike
% raster generated by this code is used in that function.


%% FIGURE 1: CA1 place field examples
fmr1CircTrack_x_placeCellTuning(group)

%% FIGURE 2: CA1 place cell properties
fmr1CircTrack_x_plotPlaceCellProperties(group)

%% FIGURE 3: Theta phase precession
fmr1CircTrack_x_phase_precession(group)

%% FIGURE 4: Decoding 
% See fmr1CircTrack_5_... above

%% FIGURE 5: Theta sequence examples and properties
fmr1CircTrack_x_decodeByThetaCycle_v2(group)

%% FIGURE 6: Example replay events and replay event properties
fmr1CircTrack_x_plotReplayEvents(group) %plots the example replay events (A-B)
fmr1CircTrack_x_plotReplayProperties(group) %cretures the data plots (C-F)

%% FIGURE 7: CA1 place cell firing during replay events
fmr1CircTrack_x_plotSingleCell_replay(group) %plots the firing properties (A-C)
fmr1CircTrack_x_ISIschematic(group) %creatures ISI schematic (D)
fmr1CircTrack_x_replayEventISI(group) %plots the inter-spike interval data plots (E-F)

%% FIGURE 8: Replay event LFP and oscillatory properties
fmr1CircTrack_x_replayEvent_TFR(group) %plots the TFR and LFP data plots (A-D)
fmr1CircTrack_x_ripplesPerReplay(group) %plots the number of ripples per replay (E)

